<MyGrid>:
    name: name
    email: email
    cols: 2
    size: root.width-200, root.height-200

    GridLayout:
        cols: 1
	size: root.width-200, root.height-200
	pos: 100, 100

	GridLayout:
	    cols:2
	    Label:
	    	text: "name"
	
            TextInput:
	        id: name
		multinline: False
	    
	    Label:
		text: "email"

            TextInput:
	        id: name
		multinline: False
	Button:
	    text:"Submit"
	    on_press: root.btn 
	
